# Test Python package by pytest.

name: Test Python Package

on: [push]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install numpy
        pip install matplotlib
        conda install -c conda-forge gdal
        pip install pytest
    - name: Install package
      run: pip install .
    - name: Test package
      run: pytest
